ha1[0]=LA
hb1[0]=LB
hc1[0]=LC
hd1[0]=LD
he1[0]=LE
hf1[0]=LF
hg1[0]=LG
hh1[0]=LH

hi1[0]=LI

hj1[0]=LJ

hk1[0]=LK

hl1[0]=LL

hm1[0]=LM
hn1[0]=LN
ho1[0]=LO
hp1[0]=LP

hq1[0]=LQ
hq2[0]=LQ
hq3[0]=LQ
hq4[0]=LQ
hq5[0]=LQ

hr1[0]=LR


ra[0]=LA
ra[1]=EA_F
ra[2]=EA_B
ra[3]=EA_H
ra[bridged]=true

rb[0]=LB
rb[1]=EB_C
rb[2]=EA_B
rb[3]=EB_E
rb[bridged]=true

rc[0]=LC
rc[1]=EB_C
rc[2]=EC_D
rc[3]=EC_IJ

rd[0]=LD
rd[1]=EC_D
rd[2]=ED_E
rd[3]=ED_N

re[0]=LE
re[1]=EB_E
re[2]=ED_E
re[3]=EE_KL

rf[0]=LF
rf[1]=EA_F
rf[2]=EF_G
rf[3]=EF_KL

rg[0]=LG
rg[1]=EG_H
rg[2]=EF_G
rg[3]=EG_Q

rh[0]=LH
rh[1]=EA_H
rh[2]=EG_H
rh[3]=EH_IJ

rij[0]=LI
rij[1]=LJ
rij[2]=EIJ_P
rij[3]=EIJ_O
rij[4]=EH_IJ
rij[5]=EC_IJ

rkl[0]=LL
rkl[1]=LK
rkl[2]=EF_KL
rkl[3]=EKL_R
rkl[4]=EKL_M
rkl[5]=EE_KL

rm[0]=LM
rm[1]=EN_M
rm[2]=EKL_M

rn[0]=LN
rn[1]=EN_O
rn[2]=EN_M
rn[3]=ED_N

ro[0]=LO
ro[1]=EIJ_O
ro[2]=EN_O

rp[0]=LP
rp[1]=EP_Q
rp[2]=EIJ_P

rq[0]=LQ
rq[1]=EQ_R
rq[2]=EP_Q
rq[3]=EG_Q

rr[0]=LR
rr[1]=EKL_R
rr[2]=EQ_R

rq[image]="kathara/quagga_dhcp"
rb[port]="80:80/tcp"