subnet 172.19.0.0 netmask 255.255.255.0 {
  range 172.19.0.3 172.19.0.253;
  option routers 172.19.0.254;
  option domain-name-servers 10.100.0.1, 8.8.8.8;
  option domain-search "chipana.izo";
  option broadcast-address 172.19.0.255;
  default-lease-time 300;
  max-lease-time 300;
}